# Generated by Django 3.2.8 on 2021-10-31 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100, null=True)),
                ('teacher_type', models.CharField(choices=[('principal', 'Principal Investigator'), ('regular', 'Regular Supervisor')], default='regular', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('staff', 'Staff')], default='student', max_length=15)),
                ('regestered', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(default='Applied Chemistry and Chemcal Engineering', max_length=255)),
                ('university', models.CharField(default='University of Chittagong', max_length=255)),
                ('educational_background', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_extension', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Users Extension',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=15, null=True)),
                ('student_type', models.CharField(choices=[('thesis', 'Thesis'), ('senior', 'Senior'), ('nondegree', 'Non Degree')], default='nondegree', max_length=15)),
                ('session', models.CharField(max_length=15, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
